version: "3.3"
services:
  api:
    image: docker.pkg.github.com/hellerphilipp/tivok-api/tivok-api:0.1
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_USER: tivok
      DB_PORT: 5432
      DB_PASSWORD: ${POSTGRES_PASSWORD_PROD}
      DB_DATABASE: tivok
      JWT_TENANT: ${JWT_TENANT}
    depends_on:
      - postgres
  postgres:
    image: postgres:9.4
    restart: unless-stopped
    environment:
      POSTGRES_DB: tivok
      POSTGRES_USER: tivok
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_PROD}
    volumes:
      - ./dbdata:/var/lib/postgresql/data
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/var/www
      - ./keys:/etc/nginx/keys
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx-ssh.conf:/etc/nginx/nginx-ssh.conf
      - ./nginx/logs/:/var/log/nginx
    depends_on:
      - api
      - postgres